name: E2E tests
on:
  workflow_dispatch:
    inputs:
      # target_environment:
      #   type: environment
      #   required: true
      #   description: 'Select environment'
      target_environment:
        type: choice
        required: true
        description: 'Select environment'
        options:
          - homolog
          - local
      browser:
        type: choice
        required: true
        description: 'Select a browser'
        options:
          - chromium
          - firefox
          - webkit
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment:
      name: homolog # Especifica o ambiente de staging
      url: https://bikeboard-homolog.vercel.app
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps ${{ github.event.inputs.browser }}
      - name: Run E2E tests
        run: echo "VAR is ${{github.event.inputs.target_environment}}"
        # run: BASE_URL=${{ vars.HOST }} npx playwright test --project=${{ github.event.inputs.browser }}
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ github.event.inputs.browser }}
          path: playwright-report/
          retention-days: 30