name: E2E tests
on:
  env:
    local: http://localhost:3000
    homolog: https://bikeboard-homolog.vercel.app
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: 'Select environment'
        options:
          - local
          - homolog
      browser:
        type: choice
        required: true
        description: 'Select a browser'
        options:
          - chromium
          - firefox
          - webkit
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps ${{ github.event.inputs.browser }}
      - name: Run E2E tests
        run: BASE_URL=${{ github.event.inputs.environment}} npx playwright test --project=${{ github.event.inputs.browser }}
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ github.event.inputs.browser }}
          path: playwright-report/
          retention-days: 30